### ISSUE TITLE
Not working with ecto 2.1

### ISSUE THREAD

**Issue by boriscy** [bryanjos/geo#54]
I have defined a file in my phoenix project in `lib/postgres_types.ex`
```elixir
Postgrex.Types.define(Publit.PostgresTypes,
                      [Geo.PostGIS.Extension] ++ Ecto.Adapters.Postgres.extensions(),
                      [json: Poison])
```
and also set the config `test.exs`

```elixir
...
config :publit, Publit.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "publit_test",
  hostname: "localhost",
  pool: Ecto.Adapters.SQL.Sandbox,
  types: Publit.PostgresTypes
```

and generates this error
Compiling 1 file (.ex)

> == Compilation error on file lib/postgres_types.ex ==
> ** (UndefinedFunctionError) function Geo.PostGIS.Extension.init/1 is undefined or private. Did you mean one of:
> 
>       * init/2
> 
>     Geo.PostGIS.Extension.init([])
>     lib/postgrex/type_module.ex:704: Postgrex.TypeModule.configure/1
>     (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
>     lib/postgrex/type_module.ex:11: Postgrex.TypeModule.define/3
>     (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

If I remove the extension (Geo.PostGIS.Extension) from `lib/postgres_types.ex` it compiles
```elixir
Postgrex.Types.define(Publit.PostgresTypes,
                      Ecto.Adapters.Postgres.extensions(),
                      [json: Poison])
```

**Comment by bryanjos** [comment]
Hi, just to make sure, are you using geo version 1.3.0?

**Comment by boriscy** [comment]
Thanks that was the problem, upgraded and working. needed to override poison for upgrade
